language:      node_js
git:
  depth:       3
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp dist
cache:
  directories:
    - node_modules
notifications:
  email:       false
deploy:
  provider: firebase
  token:
    secure: "YOUR ENCRYPTED token"
